### ISSUE TITLE
App crashed after error

### ISSUE THREAD

**Issue by MickaNoob** [L1teD/cs2-WeaponPaints-website#38]
Hi, 
Small error sometimes web app crash i need to restart it.

`Failed to verify assertion InternalOpenIDError: Failed to verify assertion
    at /var/www/html/ws/node_modules/@passport-next/passport-openid/lib/passport-openid/strategy.js:184:36
    at _verifyAssertionData (/var/www/html/ws/node_modules/openid/openid.js:984:14)
    at openid.verifyAssertion (/var/www/html/ws/node_modules/openid/openid.js:937:10)
    at openid.RelyingParty.verifyAssertion (/var/www/html/ws/node_modules/openid/openid.js:68:10)
    at Strategy.authenticate (/var/www/html/ws/node_modules/@passport-next/passport-openid/lib/passport-openid/strategy.js:183:24)
    at attempt (/var/www/html/ws/node_modules/passport/lib/middleware/authenticate.js:378:16)
    at authenticate (/var/www/html/ws/node_modules/passport/lib/middleware/authenticate.js:379:7)
    at Layer.handle [as handle_request] (/var/www/html/ws/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/ws/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/var/www/html/ws/node_modules/express/lib/router/route.js:119:3)
/var/www/html/ws/node_modules/mysql2/promise.js:112
    const localErr = new Error();
                     ^

Error: Incorrect integer value: 'undefined' for column `absynthium_game`.`wp_player_gloves`.`weapon_defindex` at row 127
    at PromisePoolConnection.execute (/var/www/html/ws/node_modules/mysql2/promise.js:112:22)
    at query (/var/www/html/ws/src/database/db.js:9:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Socket.changeGloves (/var/www/html/ws/src/listeners/weapon.listener.js:20:13) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sql: "UPDATE wp_player_gloves SET weapon_defindex = 'undefined' WHERE steamid = 76561199745725955",
  sqlState: '22007',
  sqlMessage: "Incorrect integer value: 'undefined' for column `absynthium_game`.`wp_player_gloves`.`weapon_defindex` at row 127"
}

Node.js v23.1.0
[nodemon] app crashed - waiting for file changes before starting...
`

**Comment by L1teD** [comment]
Remove `sessions` table and restart the app
Also you can wrap app under PM2 or systemd service, to have auto-restart

**Comment by MickaNoob** [comment]
Ok it's done, 

I will check if i got this error again
